services:
  backend:
    build:
      context: ./backend
    container_name: infra-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/code/uploads
      - ./backend/firebase_service_account.json:/code/firebase_service_account.json:ro


  postgres:
    image: postgis/postgis:15-3.3
    container_name: infra-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infra_db
    ports:
      - "5433:5432"
