from enum import Enum

class IssueState(str, Enum):
    SUBMITTED = "SUBMITTED"
    AUTO_REJECTED = "AUTO_REJECTED"
    UNDER_VERIFICATION = "UNDER_VERIFICATION"
    COMMUNITY_REJECTED = "COMMUNITY_REJECTED"
    VERIFIED = "VERIFIED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    COMMUNITY_REVIEW = "COMMUNITY_REVIEW"
    RANKED = "RANKED"